# Generated by Django 6.1 on 2026-08-18 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('idade', models.IntegerField(validators=[django.core.validators.MinValueValidator(18)], verbose_name='Idade')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
